"""Add chat and message models

Revision ID: 05330cd0c6a2
Revises: 1b3eb29d6b36
Create Date: 2024-12-02 02:11:20.393264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05330cd0c6a2'
down_revision = '1b3eb29d6b36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['sender_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('chats', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
