"""Add AdminActivityLog and update Administrator model

Revision ID: 256bb5f20a24
Revises: 92d00de21f46
Create Date: 2024-11-20 15:01:57.465087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '256bb5f20a24'
down_revision = '92d00de21f46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_activity_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['administrators.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admin_activity_logs')
    # ### end Alembic commands ###
