"""Add country to Delivery model

Revision ID: 6f46964326b2
Revises: a44a5e52b0ab
Create Date: 2024-12-01 04:48:02.690424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f46964326b2'
down_revision = 'a44a5e52b0ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deliveries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('special_instructions', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deliveries', schema=None) as batch_op:
        batch_op.drop_column('special_instructions')

    # ### end Alembic commands ###
