"""Add cascading delete to Product and ProductImage models

Revision ID: 753500bfdcdd
Revises: 4027dbb7e7ae
Create Date: 2024-11-26 15:24:12.552761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '753500bfdcdd'
down_revision = '4027dbb7e7ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_images', schema=None) as batch_op:
        batch_op.drop_constraint('product_images_product_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'products', ['product_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_images', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('product_images_product_id_fkey', 'products', ['product_id'], ['id'])

    # ### end Alembic commands ###
