"""adding cart

Revision ID: e895d77447ff
Revises: f8dba903a0bc
Create Date: 2024-11-28 12:08:37.084770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e895d77447ff'
down_revision = 'f8dba903a0bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('product_price', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('total_price', sa.Float(), nullable=False))
        batch_op.drop_column('price')
        batch_op.drop_column('stock')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stock', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.drop_column('total_price')
        batch_op.drop_column('quantity')
        batch_op.drop_column('product_price')
        batch_op.drop_column('product_name')

    # ### end Alembic commands ###
